version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-svc
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "8080:80"
    environment:
      MYSQL_HOST: mysql-svc
      MYSQL_DB: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./app:/var/www/html

volumes:
  mysql_data: