apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: php-mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc
  namespace: php-mysql
spec:
  selector: { app: php-app }
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: php-svc-nodeport
  namespace: php-mysql
spec:
  selector: { app: php-app }
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: php-app